### ISSUE TITLE
/api-dcos is not working by default

### ISSUE THREAD

**Issue by mastersilv3r** [godspeedsystems/gs-plugins#115]
Developer needs to set  `docs.endpoint`. If it is not set. then swagger docs dont open at /api-docs as promised in documentation
```yaml
type: express
portL 3000
docs:
   endpoint: /some_url
```
