### ISSUE TITLE
JWT AUth changes in express http 

### ISSUE THREAD

**Issue by mastersilv3r** [godspeedsystems/gs-plugins#135]
## The Problem 

- [x] Currently http auth configuration allows you to set jwt config at top level. Allow it to set within an `authn` key. Look first within the authn key. After that look for jwt key at top level of config (like it was in V1).

- [x] After enabling jwt a developer should not need to set authn: true explicitly in all the even definitions. Following zero-trust policy, he should set authn: false explicitly to disable authn for all event definitions.

## The Solution
In the below yaml setting jwt at either level should work.
```yaml
type: express
port: 3000
docs:
  endpoint: /api-docs

request_body_limit: 20000 #bytes
file_size_limit: 50000 #bytes
# jwt:
#     secretOrKey: mysecret
#     audience: mycompany
#     issuer: mycompany
authn:
  jwt:
    secretOrKey: mysecret
    audience: mycompany
    issuer: mycompany
```
## How will we solve

Changes in express plugin

## Test Cases

(Provide a list of test cases for the new feature.)
