### ISSUE TITLE
Prisma datasource add support for authz permissions

### ISSUE THREAD

**Issue by mastersilv3r** [godspeedsystems/gs-plugins#150]
> Note: this plugin is partly released as v2 of this plugin with the features mentioned below with ticked checkboxes. This is under development and latest code can be found on the main branch of this repo.

## The Problem 

Currently Prisma datasource does not support row and columns level authorization access as explained supported by [framework's authz](https://github.com/godspeedsystems/gs-node-service/issues/736)

## The Solution
Allow user to access database via prisma queries using the following method

- [x] If can_access or no_access is set, the API caller of Prisma will not be able to specify 
   - [x] `where` clause on columns not allowed. This includes direct field match, and nested `AND` and `OR` queries
   - [x] Nor will he able to `include` the fields not allowed
- [x] When `can_access` is present `no_access` is to be ignored
- [x] If user is not allowed to access something, an error will not be thrown. The user will simply be returned empty data, whether empty rows (in case his where query trespasses access boundaries) or empty fields (in case all the fields he asked are not allowed to access) 

## How will we solve
Make changes inPrisma.ts file

### Case 1
```
authz:
      - id: authz_cases
        fn: com.gs.switch
        value: <%inputs.user.role%>
        cases:
          admin:
            - fn: com.gs.transform
              args:
                success: true # Full access
          manager:
            - fn: com.gs.transform
              args:
                success: true #Restricted access
                data:
                  where: 
                    id: 19
                  can_access: ['pan_number']
```
#### Tests
```
//Query
{

"where": {"id": 19}, or "where": {"AND": [{"id": 19}]} or "where": {"OR": [{"AND":[{"id": 19}, {"pan_number": "AKJPG8855"}]}]},
"select": {"pan_number": true}
}
//Result for manager
[]
//Result for admin
[
  {
    "pan_number": "AKJPG8855"
  }
]
```
```
//Query
{

"where": {"AND": [{"id": 19}]},
"select": {"pan_number": true}
}
//Result for manager
[]
//Result for admin
[
  {
    "pan_number": "AKJPG8855"
  }
]
```
```
Query
{

"select": {"pan_number": true}
}
Result for admin - all matching rows
[
  {
    "pan_number": "AKJPG8855"
  },
 {
    "pan_number": "JHDDFD74"
  },
 {
    "pan_number": "JHUJHG56"
  }
]
Result for manager - only row with id: 19
[
  {
    "pan_number": "AKJPG8855"
  }
]

```
