### ISSUE TITLE
Salesforce as a plugin

### ISSUE THREAD

**Issue by srihari-godspeed** [godspeedsystems/gs-plugins#94]
### What we need

salesforce-as-datasource-as-eventsource plugin for godspeed framework. it should support as both datasource(p0) as well as eventsoucre(p1). it should support all the methods available in the [jsforce documentation](https://jsforce.github.io/document/)

### How we will approach 

```yaml
type: salesforce
    # Please Check  https:#jsforce.github.io/document/

    #1. Username and Password Login
    # you can change loginUrl to connect to sandbox or prerelease env.
    # loginUrl : 'https:#test.salesforce.com'

    #2. Username and Password Login (OAuth2 Resource Owner Password Credential)
    oauth2:
        # you can change loginUrl to connect to sandbox or prerelease env.
        # loginUrl : 'https:#test.salesforce.com',
        clientId : '<your Salesforce OAuth2 client ID is here>'
        clientSecret : '<your Salesforce OAuth2 client secret is here>'
        redirectUri : '<callback URI is here>'

    #3. Session ID
    serverUrl : '<your Salesforce server URL (e.g. https:#na1.salesforce.com) is here>'
    sessionId : '<your Salesforce session ID is here>'

    #4. Access Token
    instanceUrl : '<your Salesforce server URL (e.g. https:#na1.salesforce.com) is here>'
    accessToken : '<your Salesforrce OAuth2 access token is here>'

    #5. Access Token with Refresh Token
    oauth2:
        clientId : '<your Salesforce OAuth2 client ID is here>'
        clientSecret : '<your Salesforce OAuth2 client secret is here>'
        redirectUri : '<your Salesforce OAuth2 redirect URI is here>'
    instanceUrl : '<your Salesforce server URL (e.g. https:#na1.salesforce.com) is here>'
    accessToken : '<your Salesforrce OAuth2 access token is here>'
    refreshToken : '<your Salesforce OAuth2 refresh token is here>'

username: <% config.salesforce_username %>
password: <% config.salesforce_password %>
```
* User can use any of the steps mentioned above and login to salesforce
* After logging in user should be able to use salesforce as datasource and as well as eventsource

 
### Workflow example

```yaml
id: salesforce
tasks:
  - id: fist_task
    fn: datasource.salesforce.sobject.Account.create
    args:
      - Name: 'Account #1'
      - Name: 'Account #2'
      - Name: 'Account #3'
```
